version: "3.9"

services:
  db:
    image: postgres:15
    container_name: gravity_postgres
    environment:
      POSTGRES_DB: gravity_fitness
      POSTGRES_USER: gravity_user
      POSTGRES_PASSWORD: gravity_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gravity_net

volumes:
  postgres_data:

networks:
  gravity_net:
